# Comic Generation Submodule
from .comic_generator_ui import ComicGeneratorUI
from .comic_generator_logic import generate_comic_panel, create_comic_strip
from .scene_generator import generate_scene_with_dialogue
from .panel_generator import create_comic_sequence
from .stable_diffusion_comic import generate_scene_with_generated_dialogue
from .train_stable_diffusion import fine_tune_stable_diffusion
